[package]
name = "pyref"
version = "0.1.0"
edition = "2021"
authors = ["Harlan Heilman Harlan.Heilman@wsu.edu"]
description = "Enable running pyref workloads in Python"
license = "GPL-3.0"
repository = "https://github.com/WSU-Carbon-Lab/pyref"
documentation = "https://docs.rs/pyref/latest"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyref"
path = "src/lib.rs"

[dependencies]
astrors = "0.1.8"
notify = "6.1.1"
polars = "0.42.0"
polars-core = "0.42.0"
pyo3 = "0.20.0"
pyref-core = "0.2.4"
