[package]
authors = ["Harlan Heilman Harlan.Heilman@wsu.edu"]
description = "Enable running pyref workloads in Python"
documentation = "https://docs.rs/pyref/latest"
edition = "2021"
license = "GPL-3.0"
name = "pyref_rs"
repository = "https://github.com/WSU-Carbon-Lab/pyref"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "pyref_rs"
path = "src/lib.rs"

[dependencies]
astrors-fork = "0.1.10"
numpy = "0.21.0"
polars-core = "0.41.1"
pyo3 = "0.21.0"
pyo3-polars = "0.15.0"
pyref-core = "0.3.7"
