[[project]
name = "reflutils"
authors = [{name = "Harlan Heilman", email = "Harlan.Heilman@wsu.edu"}]
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "requests"
]

[project.optional-dependencies]
dev = [
    "pytest"
]
