name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: './python/**/*.py'
          args: "format $($(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA -- '*.py')) --check --diff"
