name: Python Chores

on: [push, pull_request]

jobs:
  lint-and-check:
    name: Build (${{ matrix.os }})

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Ruff Format
      - uses: chartboost/ruff-action@v1
        with:
          args: "format ./pyproject.toml"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Maturin Build
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          command: publish
